### ISSUE TITLE
It seems that there is no weight file for MemNet in your cloud driver

### ISSUE THREAD

**Issue by joy-logistics** [Lornatang/MemNet-PyTorch#1]
Hi,
I look up your weights Biadupan and Google Driver. It seems that there is no weight file for MemNet. Could you please kindly upload them? thanks.

**Comment by Lornatang** [comment]
yeah

**Comment by Lornatang** [comment]
Sorry, I remembered, the model was not trained....

**Comment by joy-logistics** [comment]
never mind. Thanks again for your kindly response :)
